# -*- coding: utf-8 -*-
"""Shopping List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gus7G0hnmDma9NVy9iDWOb0UrHKeEby-
"""

from google.colab import drive
drive.mount('/content/drive')

#import the .txt file from drive to display the items available
from google.colab import drive
import pandas as pd
#drive.mount('/content/drive')
print("Items list")
#drive/MyDrive/Items.txt
def list():
  f = open("Items.txt", "r")
  print(f.read())

list()

import os,sys,time

# Taking input from the user
name = input("Enter your name: ")

# Output
print("Hello", name)

sl = []

#shopping list -> sl
#bill -> bill

#function for main menu
def mainScreen():
	os.system('cls')
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print("        SHOPPING LIST    ")
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print("\n\nYour basket contains",len(sl),"items.\n")
	print("Please choose from the following options:\n")
	print("(a)dd to the list")
	print("(d)elete from the list")
	print("(q)uit the program")
	choice = input("\nchoice: ")
	if len(choice) > 0:
		if choice.lower()[0] == "a":
			addScreen()
		elif choice.lower()[0] == "d":
			deleteScreen()
	 	#elif choice.lower()[0] == "d":
			#checkOut()
		elif choice.lower()[0] == "q":
			quit()
		else:
			mainScreen()
	else:
		mainScreen()

#function for adding items
def addScreen():
	global sl
	global bill
	os.system('cls')
	print('\n')
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print("        ADD SCREEN    ")
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print("\n")
	print("From the list above, please enter the name of the item that you want to add.")
	print("Press ENTER to return to the main menu.\n")
	item = input("\nItem: ")
	if len(item) > 0:
		sl.append(item)
		print("Item added :-)")
		saveList()
		time.sleep(1)
		addScreen()
	else:
		mainScreen()

#function for deleting items
def deleteScreen():
	global sl
	global bill
	os.system('cls')
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print("       DELETE SCREEN    ")
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print("Current items in basket:")
	count = 0
	for item in sl:
		print(count, " - ", item)
		count = count + 1
	print('\n')
	print("Press the number of the item to delete\nIf not press enter to go back to the mainscreen.")
	choice = input("number: ")
	if len(choice) > 0:
		try:
			del sl[int(choice)]
			print("Item deleted...")
			saveList()
			time.sleep(1)
		except:
			print("Invalid number")
			time.sleep(1)
		deleteScreen()

	else:
		mainScreen()


#function for saving items
def saveList():
		f = open("shopping2.txt", "w")
		for item in sl:
			f.write(item+"\n")
		f.close()

#function after quiting from the code
def quit():
  print('Here is your alphabetized shopping list.')
  sl.sort()
  for listitem in sl:
    print(listitem)
  print("*********Thank You********")
  print("Hope to see you back soon!")

mainScreen()